apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: elchino
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tian11qb/sebastian-front-react-vite-tailwind:lastest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
